### ISSUE TITLE
Pickle model

### ISSUE THREAD

**Issue by mcreixell** [meyer-lab/resistance-MS#228]
The model finished running but the stackoverflow [post](https://stackoverflow.com/questions/11801284/how-to-overwrite-the-dump-load-methods-in-the-pickle-class-customizing-picklin) doesn't seem to be very clear to me on how to unpickle it. The file is tiny now so looks like it worked.  

![Screen Shot 2020-09-29 at 10 42 51 AM](https://user-images.githubusercontent.com/46428799/94596111-8d7eec00-0240-11eb-9d54-6807c13e46d3.png)

**Comment by mcreixell** [comment]
PS This is my `__getstate__` function:

![Screen Shot 2020-09-29 at 10 51 45 AM](https://user-images.githubusercontent.com/46428799/94596955-c53a6380-0241-11eb-8bff-fd55229d9e2c.png)

**Comment by aarmey** [comment]
You unpickle it like normal.

**Comment by aarmey** [comment]
Oooh, I guess it wants a set state attribute. Set state gets passed a dict of the member variables, so inside of it you want to make a new instance of PAM250 and then set the various stuff inside it.

**Comment by mcreixell** [comment]
A new instance of PAM250 or MassSpecClustering? So in `__getstate__(self)` should I just return a `state` variable with `self.__dict__.copy()` after deleting background, which should be passed to `__setstate__(self, newstate)`? In theory I wouldn't need to modify anything else in the latter because I already deleted the background in __getstate__? 

![Screen Shot 2020-09-29 at 11 27 20 AM](https://user-images.githubusercontent.com/46428799/94600446-be621f80-0246-11eb-9516-605f371d6f13.png)

**Comment by aarmey** [comment]
A new PAM250:

```
def __setstate__(self, newstate):
newP = PAM250(None, None, newstate['SeqWeight'])
newP.weights = newstate['weights']
newP.logWeights = newstate['logWeights']
return newP
```

You'll need to adjust __init__() in PAM250 so that it's fine with background being None and just doesn't set it.

**Comment by mcreixell** [comment]
Wouldn't this just result in pickling these two PAM250 attributes only? We wouldn't have a `MassSpecClustering` class. What would `__getstate__` be then?

**Comment by aarmey** [comment]
No, you'll get back everything that you pickled. This just handles how this particular class is unpicked.

**Comment by aarmey** [comment]
`__getstate__()` should be what you already have.

**Comment by aarmey** [comment]
If this doesn't work, point me to a branch and how to run the unpickling—I can take a look.

**Comment by mcreixell** [comment]
I'm trying to push my branch `Figure_M2` but for some reason it's like the old super large pickled file of the model is still present. Git is trying to push it which is causing the error below:


![Screen Shot 2020-09-29 at 1 47 56 PM](https://user-images.githubusercontent.com/46428799/94614041-6208fb00-025a-11eb-8ebd-1bcd402f63c1.png)

**Comment by aarmey** [comment]
Probably because the commit still exists locally on your account. https://sethrobertson.github.io/GitFixUm/fixup.html

**Comment by mcreixell** [comment]
Would it be safe to remove anything larger than 500MB?

![Screen Shot 2020-09-29 at 2 20 47 PM](https://user-images.githubusercontent.com/46428799/94617754-f9704d00-025e-11eb-83f1-8c6378f66cca.png)

**Comment by aarmey** [comment]
Sure.

**Comment by mcreixell** [comment]
Using Aretha, I'm trying to install [bfg](https://rtyley.github.io/bfg-repo-cleaner/) and apparently the easiest [way](https://github.com/rtyley/bfg-repo-cleaner/issues/106) is using `brew`. I tried installing `brew` but after doing so it still says: `command 'brew' not found`. During the installation process this warning appeared: `Warning: /home/marcc/.linuxbrew/bin is not in your PATH.` What am I doing wrong here?

**Comment by aarmey** [comment]
It’s not easy to install bfg on Aretha. What prevented you from just deleting the commit rather than filtering out the file like this?

It looks like you can download bfg and just run it on your account. See the Java command here: https://rtyley.github.io/bfg-repo-cleaner/

**Comment by aarmey** [comment]
Or just copy over the file changes to a new branch manually.

**Comment by mcreixell** [comment]
The command I found to delete the commit (`git rebase -p --onto SHA^ SHA`) warns about the following: "However, please be warned. If some of the commits between SHA and the tip of your branch are merge commits, it is possible that git rebase -p will be unable to properly recreate them." So at first looked like `bfg` was easier and safer. I will just open a new branch.

**Comment by mcreixell** [comment]
Unfortunately looks like the file size still remains the same... Which is surprising because the background is set to `None` as you can see below. I'm currently running the binomial model for comparison.  

![Screen Shot 2020-10-01 at 1 06 39 PM](https://user-images.githubusercontent.com/46428799/94857861-03bd5300-03e7-11eb-8d52-75ca2226e13f.png)

**Comment by aarmey** [comment]
Where can I find the code you are using?

**Comment by mcreixell** [comment]
it's on `pickleCPTAC` but the Binomial model is currently running and I haven't pushed the latest edits. For instance, you'll still see `deepcopy` instead of `copy`. 1 iteration out of 3 almost complete. Should I stop it?

**Comment by mcreixell** [comment]
(It just completed first iteration after 86 minutes)

**Comment by aarmey** [comment]
You can commit while it's running

**Comment by aarmey** [comment]
I bet what it's because I missed deleting the matrix from `self.dist`. This is also a PAM250 class with the matrix stored inside.

https://github.com/meyer-lab/resistance-MS/blob/fadd0a9b00a867ef46fd4eec00822c5dfacfb13a/msresist/clustering.py#L30

**Comment by mcreixell** [comment]
Just committed.

**Comment by aarmey** [comment]
I don't see anything else that would affect the size, so it's probably this. You can add the line to delete this. Note that you can unpickle, delete, and then re-pickle. You probably don't need to run the fitting again.

**Comment by mcreixell** [comment]
Nooo, I just deleted the file. Is there any way to recover it? I didn't commit it but I git -A'ed it.

**Comment by mcreixell** [comment]
I think I found a way.

**Comment by mcreixell** [comment]
Finallyyy, I just pushed both models. I've been dreaming about this moment. I'm closing this issue forever. 

![Screen Shot 2020-10-02 at 12 19 01 PM](https://user-images.githubusercontent.com/46428799/94961409-755dd580-04a9-11eb-813b-87cbf726e80c.png)
