### ISSUE TITLE
Unpickle cython object

### ISSUE THREAD

**Issue by mcreixell** [meyer-lab/resistance-MS#240]
Looks like pickle is struggling to load the Cython class unfortunately. Yesterday I was reading about ways to pickle/unpickle Cython objects but doesn't seem easy and requires us to use methods such as getstate setstate that would interact with the model, as was occurring when we tried this in the past. I think we made sure that unpickling worked before the Cython edits but not after, so I think this is why it's not working now. I haven't made any changes so If you wanted to run this, you could create a new branch off master and go to `FigreM3-TumorvsNAT.ipynb`, section "Run Model". @aarmey 

<img width="762" alt="Screen Shot 2020-10-13 at 8 04 00 AM" src="https://user-images.githubusercontent.com/46428799/95878992-b4521d80-0d2a-11eb-9d7c-341bcb47d660.png">

**Comment by mcreixell** [comment]
This is the best article I found about this:

https://snorfalorpagus.net/blog/2016/04/16/pickling-cython-classes/

**Comment by mcreixell** [comment]
I'm surprised this is happening because I think I pickled this before merging the cython changes... so in theory this pickled objects should be pythonic.

**Comment by aarmey** [comment]
When pickle tries to load something it uses the corresponding code to do so. In other words, a pickle object is sometimes just a link to the code used to reconstruct the object.

Is pickling strictly necessary? It's, what, 20 mins to fit, right?

**Comment by mcreixell** [comment]
Hmm it varies, but yes in general I'd say it's 20-30minutes per fitting, so 60-90 in total. Beyond time, I guess pickling would be useful, even with the AXL data, because that way we could make sure we're always using the same model across figures. Otherwise I'd have to run the model for figure3 and again for figure 4, and again for figure 5, etc. and I'd guess that the centers would be different in each of them.

**Comment by mcreixell** [comment]
I'll try to see how different different model fittings are with the AXL data set.

**Comment by aarmey** [comment]
Ok, I think pom does this by defining properties, because their classes don't define the pickle functions. I just did this:

https://github.com/meyer-lab/pomegranate/commit/5bc182a240e7539d811c88d8e9c7b2212b874ea3

You'll want to reinstall pom (just did this on Aretha) but then try this and see if it works. Let me know what error you get if it doesn't.

**Comment by aarmey** [comment]
Also, can you write a test checking that you can pickle/unpickle? That will be easier to run than a notebook. You can just pickle/unpickle to/from a string, rather than a file, with `dumps()` and `loads()`.

**Comment by mcreixell** [comment]
I'm getting the same error

![Screen Shot 2020-10-13 at 11 25 20 AM](https://user-images.githubusercontent.com/46428799/95900466-c80b7d00-0d46-11eb-9745-34f112871392.png)

**Comment by mcreixell** [comment]
I'm seeing that the method is much more consistent now across fittings tho. Also on another note, the bug in the PCA plot was also affecting the PLSR model so now this works much better:

![Screen Shot 2020-10-13 at 11 24 09 AM](https://user-images.githubusercontent.com/46428799/95900852-55e76800-0d47-11eb-9f32-427bf14f4a08.png)

**Comment by aarmey** [comment]
You'll have to re-pickle a new fit first. That old file will continue to error.

**Comment by mcreixell** [comment]
I overwrote the same file with same name. To make sure I just changed the filename and I'm still getting the same error.

**Comment by mcreixell** [comment]
Can't dump the new fit. 

![Screen Shot 2020-10-13 at 11 40 02 AM](https://user-images.githubusercontent.com/46428799/95901883-d65a9880-0d48-11eb-9bca-351a08582226.png)

**Comment by aarmey** [comment]
Ergh. Ok, let me think about this.

**Comment by aarmey** [comment]
I implemented `__reduce__()` instead to handle the pickling: https://github.com/meyer-lab/pomegranate/commit/6834112c688710dc7a850ed3b2ed2bf24bdb9722

Try this out. Remember you'll have to reinstall pom first (just did this on Aretha).

**Comment by mcreixell** [comment]
Okay now it works great. Thanks a lot, this is going to be very helpful.
