### ISSUE TITLE
Update reconstruction error code

### ISSUE THREAD

**Issue by mcreixell** [meyer-lab/resistance-MS#250]
@aarmey I am still unsure of how to think about this. What I understood at the end is what I'm showing in the diagram below as option A. I remove a random TMT experiment per peptide, fit the model, calculate errors, and group these errors according to the amount of missingness. But the whole point of fitting with the full data first was to speed subsequent fittings up so I think that what you meant is something closer to option B. If that's the case. My main question is how to structure this for loop so that I end up with a reconstruction error per missingness group. Ideally, I'd start with a complete data set without NaNs and I would cumulatively add 25% NaNs per iteration. Since here peptides have a variable missingness of 0-90%, I'm not sure how to rationally remove data in each iteration nor how to integrate the calculated errors in each iteration. Thank you.

![IMG_7142](https://user-images.githubusercontent.com/46428799/96309336-f349d280-0fb9-11eb-801f-4ba61cce1721.jpg)

**Comment by aarmey** [comment]
Are you able to get on Zoom for a bit?
