### ISSUE TITLE
Add missingness imputation diagram

### ISSUE THREAD

**Issue by mcreixell** [meyer-lab/resistance-MS#276]
Is there an easy way to add the diagram in the first slot of figureM2.svg I made to explain how we're calculating the reconstruction error in figureM2.py? It's in the files folder. @aarmey

**Comment by aarmey** [comment]
Yes. @Farnazmdi, could you help set this up? It should be the same as in the tHMM repo.

**Comment by Farnazmdi** [comment]
Sure, will do.

**Comment by mcreixell** [comment]
Thanks!

**Comment by Farnazmdi** [comment]
I don't have permission to make a PR, could you please give me permission @aarmey?

**Comment by aarmey** [comment]
Should be fixed.

**Comment by Farnazmdi** [comment]
Thanks.
