### ISSUE TITLE
Mean-centered Frobenius norm of the difference between two matrices 

### ISSUE THREAD

**Issue by mcreixell** [meyer-lab/resistance-MS#277]
@aarmey I want to make sure I'm correctly interpreting the normalized distance between the PSSM and PSPL. The frobenius norm of the difference between both matrices should always be positive:

https://github.com/meyer-lab/resistance-MS/blob/d7ca90417c99788918aeeab7714116b990dab3f6/msresist/clustering.py#L137-L139

And the resulting matrix with all norms is then mean-centered along both axes:

https://github.com/meyer-lab/resistance-MS/blob/d7ca90417c99788918aeeab7714116b990dab3f6/msresist/figures/figure3.py#L462-L475

This means that the most negative kinases in this plot display the strongest preference for a cluster motif? 

![image](https://user-images.githubusercontent.com/46428799/99568097-02e37f00-299d-11eb-8187-9ca41efb1d71.png)

**Comment by aarmey** [comment]
That seems right to me. If you want to normalize all the distances, but like keeping them all negative, you could try dividing by the geometric mean of the distances, rather than mean centering?
