### ISSUE TITLE
FigureM2

### ISSUE THREAD

**Issue by mcreixell** [meyer-lab/resistance-MS#283]
This is what this figure currently looks like:

![figureM2](https://user-images.githubusercontent.com/46428799/102041771-482d7d80-3d9e-11eb-9f32-68ce053a6d64.png)

These are items I was thinking would make this figure final:
- Add error to minimum peptide signal in addition to average
- Compare to other imputation strategies: [GMSimpute](https://pubmed.ncbi.nlm.nih.gov/31199438/) / [DreamAI](https://www.biorxiv.org/content/10.1101/2020.07.21.214205v1.full) 
- Add legends in plots B-F.

What do you think? @aarmey

**Comment by aarmey** [comment]
Makes sense. What prevents you from going higher than 22 clusters?

**Comment by mcreixell** [comment]
24 is the highest number of clusters with the binomial method, 22 with pam250. More than this we get nans in the scores.

**Comment by aarmey** [comment]
Hmm... can you tag me in an issue saying that? I'd like to see why.

**Comment by mcreixell** [comment]
Do you think that the improvement of DDMC vs k-means/GMM seen in Supplemental Figure 5 (#334) is enough to skip the imputation evaluation?
