### ISSUE TITLE
Phosphoacceptor-specific upstream kinase prediction?

### ISSUE THREAD

**Issue by mcreixell** [meyer-lab/resistance-MS#290]
@aarmey In this plot you can see the MDS-PCA analysis wherein I'm only labeling the 5 nearest neighbor kinases for each cluster that phosphorylate a cluster's phosphoacceptor residue (e.g. cluster 4 is a pY motif, my code only labels the 5 nearest pY kinases while ignoring all pS/T kinases, even if these kinases are closer to the cluster). However, there are situations such as cluster 5 in the PC1/PC2 plot or clusters 1, 3, and 4 in PC3/PC4 where all the kinases that are close to them don't phosphorylate the clusters' phosphoacceptor residue. That's why I was thinking that maybe it would be worth running an MDS-PCA analysis in a phosphoacceptor-specific manner. That is, two analyses in parallel, all pY cluster PSSMs and kinase PSPLs on one hand, and all pS/T cluster PSSms and kinase PSPLs on the other. I think that ideally, the current set up would be able to pick up phosphoacceptor-specific differences using all the data together, but it looks like the motifs are not different enough and this analysis is not very useful if all the predicted upstream kinases can't phosphorylate their corresponding motif. What do you think?
 
<img width="1182" alt="Screen Shot 2020-11-27 at 9 48 48 AM" src="https://user-images.githubusercontent.com/46428799/100474566-c0edc380-3095-11eb-85b8-7456b535d57d.png">

**Comment by aarmey** [comment]
Sounds reasonable to me.
