### ISSUE TITLE
NaNs in PSSMs

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/resistance-MS#294]
Why do you end up with a ton of NaN's in your pssms? I'm seeing tons of warnings when I build the figures.

https://github.com/meyer-lab/resistance-MS/blob/f7296a9a7bd13fba02a787a1a2a229cf7bd131da/msresist/clustering.py#L114

**Comment by mcreixell** [comment]
I just checked and I'm not seeing any NaNs in the PSSms (`pssms = model.pssms(PsP_background=False/True)`). I think that the warnings may be due to the central position in which all are 0 except from Y, S, T.

**Comment by aarmey** [comment]
Aha. Those probably turn into -inf after log transforming. We can discuss this next time we're on Zoom. There's likely a quick fix.
