### ISSUE TITLE
Hypothesis testing

### ISSUE THREAD

**Issue by mcreixell** [meyer-lab/resistance-MS#295]
ANOVA to predict staging and Mann Whitney to predict binary problems (NAT vs tumor / mutational status).

**Comment by aarmey** [comment]
I'd suggest a seaborn stripplot, where the x-axis is cluster and the color is status (tumor or mutation).


![seaborn-stripplot-7](https://user-images.githubusercontent.com/2065146/101104339-c78da680-357f-11eb-87a8-5eca8532cbc4.png)

**Comment by mcreixell** [comment]
Great, I'll set this up later or tomorrow. Today we're imaging the YAP blots and lysing the cells for mass spec. 

On a different note, I was thinking before that I'm using both NAT and tumor samples for the hypothesis testing of the clinical stages... I'm going to run this again for NAT and tumor separately. @aarmey
