### ISSUE TITLE
Illustrating Uptream Kinase

### ISSUE THREAD

**Issue by mcreixell** [meyer-lab/resistance-MS#308]
@aarmey I was thinking that maybe instead of showing this PCA plots, a cleaner alternative could be showing the distance between the cluster coordinates and the nearest kinases in some sort of ranking? I guess it would be essentially a bar plot showing the cluster-to-kinase distance of the nearest clusters?

![image](https://user-images.githubusercontent.com/46428799/102180077-49ca7480-3e76-11eb-92a5-27bb5a5c35ae.png)

**Comment by aarmey** [comment]
Isn't that essentially what you had before?

**Comment by mcreixell** [comment]
Before we used the Frobenius norm between clusters and kinases. Here I mean making a bar plot as well but using the distances between clusters and kinases in this principal component space after multidimensional scaling via this [method](https://scikit-learn.org/stable/modules/neighbors.html) that I'm already implementing to label the 5 nearest kinases to each cluster.

**Comment by aarmey** [comment]
Yes... but MDS aims to find components that represent the distances you provide, which are the Frobenius norm. What do you think MDS is improving in this case?

**Comment by mcreixell** [comment]
MDS is helping us deal with the scale of all the matrices. I’m just trying go think of the cleanest way of illustrating these results.

**Comment by aarmey** [comment]
Yeah... I really think this is giving you the same result as the Frobenius norm. Weren't there other issues you corrected based on how the MDS results looked? If so, simply going back to the Frobenius norm might work just fine.

**Comment by mcreixell** [comment]
The two things I corrected were (i) running MDS/PCA in parallel for each phosphorylation type—which if we go back to Frobenius norm I think I should do as well—and (ii) Showing the labels of only the nearest 5 neighbors. I'll check what the results look like in both cases and decide then. If the results are mostly similar I will switch back to Frobenius norm.
