### ISSUE TITLE
Sequence improves prediction?

### ISSUE THREAD

**Issue by mcreixell** [meyer-lab/resistance-MS#354]
I re-run figureS5 a few times with the different pickled binomial models I have with varying weights and it looks like the sequence information actually helps improve prediction? @aarmey 

W = 0 (data only)
![MS5_binom0](https://user-images.githubusercontent.com/46428799/107972563-52454580-6fb4-11eb-9208-d81d05211c7e.png)

W = 15
![MS5_binom15](https://user-images.githubusercontent.com/46428799/107969628-4c4d6580-6fb0-11eb-94f6-3f1d90f2f956.png)

W = 20
![MS5_binom20](https://user-images.githubusercontent.com/46428799/107969630-4ce5fc00-6fb0-11eb-9c9d-692ce5140195.png)

W = 40
![MS5_binom40](https://user-images.githubusercontent.com/46428799/107969631-4d7e9280-6fb0-11eb-8ebc-20106bfa0093.png)

W = 50
![MS5_binom50](https://user-images.githubusercontent.com/46428799/107969632-4d7e9280-6fb0-11eb-8e19-62a9e1712d3f.png)

**Comment by aarmey** [comment]
Yep. You can summarize the overall performance by AUC.
