### ISSUE TITLE
STK11 modulates immune infiltration

### ISSUE THREAD

**Issue by mcreixell** [meyer-lab/resistance-MS#357]
In the CPTAC study [PMID: 32649874, figure 5B-C], they show how the mutated STK11 correlates with a negative effect on immune infiltration (find data below). As I was working on the text for figure 5, I was wondering if there would be an interesting way for us to use our clusters to dig into the mechanism by which this occurs. @aarmey 

'''"
The most dramatic downregulation of immune activation was in STK11 mutant tumors, with marked reductions in xCell-derived dendritic cell, natural killer T cell, and macrophage signatures (FDR < 0.05) (Figure 5B; Table S5). In striking contrast, STK11 mutant-associated NATs were enriched for dendritic cell and macrophage infiltration (FDR < 0.1) (Figure 5C). 

<img width="471" alt="Screen Shot 2021-02-16 at 10 55 06 AM" src="https://user-images.githubusercontent.com/46428799/108046886-6f762480-7045-11eb-9a84-8bc0ca0ff5e2.png">

'''"

**Comment by aarmey** [comment]
Sounds reasonable. We'll just need to make sure we're not picking up peptides from the MO themselves.

**Comment by mcreixell** [comment]
To check this, would you use the cluster centers corresponding to the STK11 mutant patients (20) and try to predict all the cell populations that they show above in B with multi task lasso? @aarmey

**Comment by aarmey** [comment]
I don't think I follow what question you are answering with the model. If you want to ask whether STK11 affects infiltration, then you should use STK11 status to predict infiltration. If you want to ask how phosphorylation affects infiltration, then use that data to predict.

**Comment by mcreixell** [comment]
In the CPTAC paper they showed that the immune infiltration of tumors is dramatically downregulated when STK11 is mutated. I was wondering if there is a way to investigate the mechanism by which this occurs. That's why I was thinking of just including the cluster centers of STK11m patients to predict the infiltration of cell populations that seem to be affected by this mutation. My hope is that these infiltration levels would be affected by a particular cluster which we could further explore.

**Comment by aarmey** [comment]
Two options:

Build a model predicting infiltration with only those clusters changed by STK status.
Build a model that predicts STK, build a model that predicts infiltration, and look for shared cluster dependencies.
