### ISSUE TITLE
Wrong normalization axis on infiltration data

### ISSUE THREAD

**Issue by mcreixell** [meyer-lab/resistance-MS#358]
I found odd that the PCA analysis of figure 5 showed that most of the variation was in PC1 but the loadings barely showed any differences: 

<img width="505" alt="Screen Shot 2021-02-17 at 12 22 14 PM" src="https://user-images.githubusercontent.com/46428799/108197512-c7328f80-711a-11eb-9164-b99545450858.png">

That's how I realized that similarly to what was happening with the clusters as we were discussing on slack, I was zscoring this data by sample instead of by cell type... I fixed this but sadly now the multitask lasso model is no longer predictive (find updated figure below, r2=0.25). I tried PLSR too and doesn't work either. 

![fig5](https://user-images.githubusercontent.com/46428799/108197423-a702d080-711a-11eb-80e0-c2c4d713bb4f.png)

However, I tried predicting whether a tumor is "cold-enriched" or "hot-enriched" which is also part of the data generated by xCell on Gillete et al. (Table S5) and the performance is decent:

![ROC_TIIC](https://user-images.githubusercontent.com/46428799/108203158-63ac6000-7122-11eb-81a7-f9a821ef3d20.png)

**Comment by mcreixell** [comment]
This is the updated figure 5 predicting hot vs cold tumors:

![figM5](https://user-images.githubusercontent.com/46428799/108207504-20ed8680-7128-11eb-98a6-ba5e884128e9.png)

**Comment by mcreixell** [comment]
I'm not sure if you get notifications if you're not tagged so just in case. @aarmey

**Comment by aarmey** [comment]
Did this data need normalization in the first place? It sounds like you can predict the degree of infiltration, but not the relative makeup of those immune cells. That's fine.

**Comment by mcreixell** [comment]
Yes, the raw xCell estimates are not normalized. They're pretty large numbers. I'm closing this then.
