### ISSUE TITLE
2 fits although nRepeats=1

### ISSUE THREAD

**Issue by mcreixell** [meyer-lab/resistance-MS#384]
I'm setting `nRepeats=1` when fitting DDMC however after a first fit it runs the model again as you can see below. Is this related to pickle? Is there any way we could avoid this? @aarmey 

![Screen Shot 2021-03-16 at 6 14 04 PM](https://user-images.githubusercontent.com/46428799/111399971-b26bfc00-86c6-11eb-8f1b-2620b642597f.png)

**Comment by aarmey** [comment]
I don't see why pickling would cause this. Have you printed out `nRepeats` in that loop to make sure it's being properly set?

The fact that PCA runs again indicates that `EM_clustering` is definitely being called again.

**Comment by mcreixell** [comment]
Solved.

**Comment by mcreixell** [comment]
nRepeats must be 0 to fit only once:

<img width="358" alt="Screen Shot 2021-03-17 at 8 24 11 AM" src="https://user-images.githubusercontent.com/46428799/111492738-3660cb00-873d-11eb-853e-290a1ca4f019.png">

**Comment by aarmey** [comment]
Ohhh because nRepeats defines the number of repeats, not original fits. Good catch.
