### ISSUE TITLE
Strip plot with mean AUC s?

### ISSUE THREAD

**Issue by mcreixell** [meyer-lab/resistance-MS#405]
Instead of this array of ROC plots (figM2), should I just make a strip plot where x=Phenotype, y=mean AUC and hue=weights? @aarmey 

<img width="763" alt="Screen Shot 2021-04-15 at 11 08 11 AM" src="https://user-images.githubusercontent.com/46428799/114917534-565fd900-9e26-11eb-88ae-886e451524d0.png">

**Comment by mcreixell** [comment]
and then maybe show this in the supplement if necessary?

**Comment by aarmey** [comment]
Yep.
