### ISSUE TITLE
Methods manuscript layout 

### ISSUE THREAD

**Issue by mcreixell** [meyer-lab/resistance-MS#406]
I was wondering if it would look best to show the validations before or after the CPTAC analysis (i.e. validations as figure 3 or 6?). The validations figure would include the AKT prediction of the EBDT paper and the ERK2 prediction of the White lab paper. @aarmey 

Figures
1. Model diagram, how it works.
2. Model more predictive using motif information. Add data showing how assignments change with different weights. 
3. Validations
4. Tumor vs NAT
5. STK11
6. Tumor infiltration

**Comment by aarmey** [comment]
I tend to like the method validation to come before the interesting results. Otherwise, you might ask why you care about the CPTAC results, if you're reading about them before showing the method works.
