### ISSUE TITLE
NEK/YAP axis

### ISSUE THREAD

**Issue by mcreixell** [meyer-lab/resistance-MS#414]
Working on the methods paper I came across this [study](https://pubmed.ncbi.nlm.nih.gov/33297404/) proposing the axis NEK1-YAP1 as a key determinant of prostate cancer progression. Our AXL cluster 5 correlates with cell viability and migration and displays a clear NEK motif. It'd be pretty cool to show this axis also occurs  in lung cancer and in the context of AXL activation. I think it would be more novel than ABL/SFK. Maybe CKII could also be interesting to explore at some point. @aarmey @scottdtaylor95 

![fig2](https://user-images.githubusercontent.com/46428799/115905331-3fdd0180-a466-11eb-841f-e9708ba5c31c.png)

**Comment by aarmey** [comment]
Interesting. I agree, though I'll have to do some reading on NEK1—I know essentially nothing about it.
