### ISSUE TITLE
Figure 3  

### ISSUE THREAD

**Issue by mcreixell** [meyer-lab/resistance-MS#423]
@aarmey A couple things I forgot to discuss during lab meeting about Figure 3:

![image](https://user-images.githubusercontent.com/46428799/116933494-7a8a2b00-ac18-11eb-8b00-57aeef7314c7.png)

1. Since the mean AUC of the different weights is not as smooth as we would like to, do you think it would be useful to maybe fit each model a few times to include confidence intervals and show that these results are reproducible?

2. Should I replicate this with different number of clusters? I think that if we show that 24 clusters minimizes the imputation error there's no need to show this but maybe it's something that reviewers would ask?

**Comment by aarmey** [comment]
1. That'd be a *little* better, but I'd rather get everything else finalized first. Maybe make a note to consider later?
2. Are you going to show imputation in this paper? I think you need something addressing the number of clusters... you could look at prediction errors across a number of clusters. I don't think you need to test every possible combination of clusters and weights.

**Comment by mcreixell** [comment]
> 1. That'd be a _little_ better, but I'd rather get everything else finalized first. Maybe make a note to consider later?
Ok, I'll keep this issue open as a reminder.
> 2. Are you going to show imputation in this paper? I think you need something addressing the number of clusters... you could look at prediction errors across a number of clusters. I don't think you need to test every possible combination of clusters and weights.
I'm currently working on the imputation figure so hopefully I will be able to show it in this paper.
