### ISSUE TITLE
Tentative Interpretation Scheme

### ISSUE THREAD

**Issue by mcreixell** [meyer-lab/resistance-MS#429]
@aarmey What do you think about combining the enriched GO processes with a STRING map of the proteins involved in these pathways? This is how it would look like in figure 5. I wanted to ask before doing the same thing with figures 6 and 7.

**Comment by mcreixell** [comment]
![image](https://user-images.githubusercontent.com/46428799/117390356-dcf65c00-aea2-11eb-8779-1df4f418a9ad.png)

**Comment by mcreixell** [comment]
Finding a good way of showing what's inside the clusters and proof-reading the text are the last two items I want to take care of before finalizing a first draft of the manuscript and ask for your review.

**Comment by aarmey** [comment]
What information does the STRING map reveal?

**Comment by mcreixell** [comment]
The interaction between the different molecules enriched in those processes. For instance PEAK1 seems to be a  key modulator or link of both Gas/Oxygen transport and cytoskeletal remodeling. It illustrates more generally what molecules are driving these GO processes and their interactions.

**Comment by mcreixell** [comment]
In cluster 12, STRING helped me see that CDKs play an important role as well

**Comment by mcreixell** [comment]
Sounds good, then I will just show the GO enrichment score bar plots.
