### ISSUE TITLE
Dasatinib Dose Response Mass Spec

### ISSUE THREAD

**Issue by mcreixell** [meyer-lab/resistance-MS#431]
@aarmey Before I set up the meeting with Jacqueline and @scottdtaylor95, I wanted to ask a question. It looks like in both biological replicates WT and KO are practically identical. I remember we discussed that maybe this is a result of mixing WT with KO labels so that in reality what we are seeing here in BR2 is only WT samples and in BR1 only KO samples but I can't recall why we ruled this possibility out. 

![DasMS_BR1](https://user-images.githubusercontent.com/46428799/117491177-779f7b00-af35-11eb-85a8-2a9ddb5f0f93.png)

![DasMS_BR2](https://user-images.githubusercontent.com/46428799/117491169-766e4e00-af35-11eb-96ae-d2779cebb597.png)

**Comment by mcreixell** [comment]
I think this could explain why the variation of overlapping peptides is so high

![OverlapError](https://user-images.githubusercontent.com/46428799/117491877-69059380-af36-11eb-8365-5572a6b08f8c.png)

**Comment by aarmey** [comment]
We ruled it out because Jacqueline was seeing that the samples went in the opposite direction. We couldn't picture how shuffling the samples would cause this. However, your plot makes it look like there isn't the problem she saw, right?

**Comment by aarmey** [comment]
Oh wait... I got your plots confused. You see the same thing.

Still, I don't see how shuffling the samples would make all the trends go in opposite directions.

**Comment by aarmey** [comment]
If you look at these on a peptide-basis, one of them must be clearly the wrong direction.
