### ISSUE TITLE
Throw data of a single well from an Incucyte Exp

### ISSUE THREAD

**Issue by mcreixell** [meyer-lab/resistance-MS#464]
@aarmey From this experiment below, something went wrong with WT UT cells treated with 1.6nM dasatinib in one of the biological replicates. The rest looks good. I guess we should repeat this experiment, we can't just throw the data of this well and keep the rest right?

<img width="404" alt="Screen Shot 2021-07-12 at 6 36 14 PM" src="https://user-images.githubusercontent.com/46428799/125376526-0cf92a00-e340-11eb-99bc-0980fc0e40dc.png">

**Comment by mcreixell** [comment]
We have 2 BRs and no TRs

**Comment by aarmey** [comment]
Should repeat.

**Comment by mcreixell** [comment]
Will do!
