### ISSUE TITLE
Word document export error

### ISSUE THREAD

**Issue by mcreixell** [meyer-lab/resistance-MS#492]
Any ideas where this might be coming from? @aarmey 

![Screen Shot 2021-09-16 at 3 57 50 PM](https://user-images.githubusercontent.com/46428799/133696048-8f22b907-9536-44a3-8430-874b77c0ccaa.png)

**Comment by aarmey** [comment]
Looks like your version of pandoc doesn't match. Why do you want to export?

**Comment by aarmey** [comment]
Oh wait... I might have fixed your issue on master. Try that.
