### ISSUE TITLE
TerminatedWorkerError: (Due to memmory?) -  in Grdisearch(n_jobs=-1)

### ISSUE THREAD

**Issue by mcreixell** [meyer-lab/resistance-MS#62]
Only one of the checks failed with the following error below. **It's coming from `plotMixedClusteringPLSR_GridSearch` in `figure2.py`**:

[0;31mTerminatedWorkerError[0m: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker. The exit codes of the workers are {SIGSEGV(-11)}
TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker. The exit codes of the workers are {SIGSEGV(-11)}

From what I've found online, it seems that this is a quite recent error from 'Gridsearch'? https://github.com/scikit-learn-contrib/skope-rules/issues/18 

It's a bit confusing to me tho the fact that all the figures are correctly displayed on Jenkins when I click on the checks that did pass. Also I don't get any errors when I run this locally on my notebook. 
`
Any suggestions? @aarmey

**Comment by MosesBomera** [comment]
I experienced this exact error after updating Windows 10 (KB 5001330), uninstalling this update resolved the error, for windows users maybe you could look into this especially if it was working before the update.
